### PR TITLE
Feature/remove base64 dependency

### PR DESCRIPTION
**Pull request by victuxbb**
To achieve avoiding use of Base64 library first of all I tryied to decouple things smooth as possible using concepts like dependency injection to be able to change base64 encoder/decoder implementation without having breaking changes, only minimal changes in the dependency graph initialization.
Also applyied good practises to class Consent like encapsulate complex build in a Factory to hide some details to our clients. 
 
This PR includes:
* Update travis configuration to add lint and tests checks
* Update jsdoc automatic configuration
* Remove dependency from base64 library
* Add dev dependency babel-register to transpile test sources
* Add dev dependency jsdom to mock atob and btoa window functions
* Add dependency injection concept as functional programming style to isolate base64 services to encode and decode
* Change ConsentString to Consent class, I'm open to hear suggestions for the name but using things like String or BigInt o Array don't sounds like a good idea for this class, also following airbnb code style, filename must match class name so PascalName.js format must be followed
* Add build graph dependencies in the main file index.js, to client only have access to a instance of ConsentFactory to create Consent objects
* Add ConsentFactory to hide encoder/decoder from client but reflect it as dependencies for Consent class
* Fix all tests
* Fix some jsdocs that were using type integer instead of number
* Fix some imports and exports following code style of airbnb as package.json seems indicate
* Pending update readme file
* Pending add runtime check with maybe something as a service like browserstack? For now has been check in chromium 65 and it works...
* Pending change version to a major update 2.0.0 because this version is breaking changes with client
* Merge conflicts related with a metadata encoder and decoder, just for now I isolated the static method as function exported to be used because technically speaking has nothing to do inside Consent class

### CODE REVIEW

**Comment by victuxbb** [comment]
A simple usage with this new code would be something like this:
```javascript
import { consentFactory, decodeMetadataString } from 'consent-string'

const data = consentFactory.createFromEncodedBase64String({
  base64EncodedString: 'BOQ7WlgOQ7WlgABACDENABwAAABJOACgACAAQABA'
})
console.log('Consent object:', data.version)
console.log('Consent object:', data.getPurposesAllowed())

const metadata = decodeMetadataString('BOQ7WlgOQ7WlgABACDAAABAAAAAAAA')
console.log('decodeMetadaString', metadata.cmpId)```

**Comment by chrispaterson** [comment]
@victuxbb thanks for doing this!  A preliminary thing, if you could update the README.md as well.  You changed the constructor and that should be documented in the method definition as well as the use-case examples.  .... Still looking through the code.

**Comment by jawadst** [comment]
Changing the structure introduces breaking changes and does not respect the Consent String SDK specification (https://docs.google.com/document/d/1csswKXYx6aK1MwQazX92G_t02zlKS7Xiolycm1V1mv4/edit#heading=h.bn1mt7odxyi6).

I think it makes the code harder to follow as well but I can accept that this part is just my opinion :)

I am not even sure I understand why we are removing the base64 dependency, assuming it is required for old browsers (IE9, mostly) and we want to support them. It means that people will have to add back the dependency themselves most of the time.

If we really want to remove it then we'll need to clearly explain in the README how to add it back as I think most use cases in the browser will want it.

As for the implementation, why not simply define a global object on the `ConsentString` class like:
```
ConsentString.Base64 = {
  atob: window.atob,
  btoa: window.btoa
};
```

And let the user override that with the library if they want to? We'd just need to add an extra check to throw an error if the atob/btoa functions are not defined on that object.

**Comment by victuxbb** [comment]
@jawadst This PR is for prepare the code to be easy to change implementation of base64 from the index.js were dependecy graph is build. If we want to support IE9 that's another topic, before my PR there was a lot of code using things like **Object.assign** or **Array.from** that aren't compatible with IE9 so I suggest to open another PR to tackle IE9 compatibility.
For now we are removing base64 because we weren't compatible with IE9 neither before nor now so we are just making lighter the build with the same compatibility level.
When we tackle IE9 compatibility we can think about using a custom polyfill for this or use base64 library or whatever but will be easy to do.

In general to our clients, we shouldn't expose private details of our implementation to solve the problem that is solving our library consent-string it's a concept of abstraction and encapsulation, you should make clients life easier through a friendly use cases of your library :)

In reference to "why not simply define a global object on the ConsentString":
* Because in OO constructors exist for that purpouse, there is no sense in creating global objects to allow global modifications
* Because ConsentString class is NOT using the atob/btoa, is using a wrapper function that includes some business stuff related with consent, not just the atob/btoa, take a look at **encodeConsentStringFactory** in **encode.js**
* Because you already can change the implementation of encoder/decoder from the index.js (dependency graph)

**Comment by victuxbb** [comment]
Keeping in mind all said I suggest:
* Change the target of this PR to a branch of feature/consent-string2 instead of master
* In that branch iterate to achieve IE9 compatibility an other stuff that we consider important, that means configure all stuff required to use browserstack and launch all tests in different OS and browsers

**Comment by jawadst** [comment]
@victuxbb Thanks for the detailed explanation and the details on IE9. I agree with you on that point (let's forget about it for this PR).

Setting aside your changes for now, I think we do want to stick to the existing interface and cannot break it (even in a new 2.0 version). We are trying to keep interfaces similar across all languages (https://docs.google.com/document/d/1csswKXYx6aK1MwQazX92G_t02zlKS7Xiolycm1V1mv4/edit#heading=h.bn1mt7odxyi6) so it seems to me that this is a constraint we cannot change.

@chrispaterson Any opinion on that?

**Comment by chrispaterson** [comment]
I agree with you @jawadst and @victuxbb.  I'd like to keep to keep the constructor interface the same -- I don't think adding the properties in a object to the constructor adds enough to warrant a breaking change.  I'm not a huge fan of code having too many paths of use.

**Comment by victuxbb** [comment]
Well, first of all I will try to explain why using an empty constructor and the setters use is a bad desing:
Your current implementation allows you to do this:
```javascript
const { ConsentString } = require('consent-string');
const consentData = new ConsentString();
consentData.getConsentString();
```
getConsentString method will throw an error because there is a conditional in the method:
```javascript
if (!this.vendorList) {
  throw new Error('ConsentString - A vendor list is required to encode a consent string');
}
```
So here you must ask yourself, why if it's **required** I'm hidding this to my client until he calls getConsentString ?
You need this conditional because you are allowing to create a ConsentString object in an **invalid state**, if you define your requirements with a good design maybe using a Factory or a Builder or whatever you will not need to fill all your code with conditionals to check if the current state of the object is valid or not, because you don't know if your client called all setters needed to get a valid state.

IMHO both of you are missunderstanting interface concept, an interface is for defining contracts about **behaviour** like "getConsentString" or "getMetadataString" but you cannot add a constructor as a method of an interface, why? because a constructor doesn't reflect behaviour, reflects requirements needed to build an object in a **valid state**

Let's put an example:

Class ConsentString should implements ConsentInterface and ConsentInterface forces you to implement his methods, so anyone following interface from IAB must have a  "getConsentString" or "getMetadataString"

Another clear example, IAB tells you that must be a way of creating a ConsentString object from a base64 string so that means that IAB must provide an **interface** of a **Factory** or a **Builder** that build ConsentString objects  so anyone can solve the problem of using an encoder and decoder in a open way.

So summarizing (TL;DR;), I think the main problem here is a **bad desing** of this "standard docs" from IAB, I think there is a mixing between standarizing data structures and fields and the way of doing things fine in a technical way.
It seems to me perfect that IAB tell me how data consent structure must be, what kind of types use in fields and what kind of use cases must be exposed to our clients but if IAB tells you to build empty objects with invalid states and do bad practises well known years ago in Object Oriented Programming something is wrong here.

**Comment by victuxbb** [comment]
Just a clarification, if being said that, if you don't feel confortable to rethink interfaces and all this stuff, I can rewrite this PR to not break changes and expose ConsentString so at least we can merge all changes of travis, jsdoc, imports etc

**Comment by chrispaterson** [comment]
@victuxbb That's all well and good but adding an object that's passed in and not type or value-checked doesn't remove the need for conditionals to verify data before encoding a consent string.   So by your logic we should remove the constructor entirely or change the constructor to accept listed parameters of 

`ConsentString(vendorList, baseString=null)`
That would build a valid-state consent string.  

I think I would be ok with that.  I'm not a fan of giant property bags of unenforcible parameters that you have to look up documentation to know what to pass.  That's my main concern.  Matching the other specs is less of a concern because other Consent String SDKs are written to for reading a Consent String.  That's why the constructor has just the string passed in.  They are decode only.  This library is handles both cases, so while constructing might put the object into an invalid state without a vendorlist passed, readying a consent string with an existing encoded string creates a valid state.  The case of building from nothing to a valid state was overlooked.

Also, I'm the one who wrote the "standard docs" of the consent string SDK.  So I can change them.

**Comment by chrispaterson** [comment]
Closing as this seems stale now.

**Pull request closed without merging**
